### ISSUE TITLE
gitment

### ISSUE THREAD

**Issue by zBorwen** [HeskeyBaozi/hexo-theme-lite#33]
登陆之后没显示评论 显示404 ... 好难受怎么搞

**Comment by HeskeyBaozi** [comment]
？？？
请问`gitment`字段怎么配置的？显示404，方便的话有截图吗？
请确保按[文档](https://github.com/HeskeyBaozi/hexo-theme-lite#cool-features)配置，即可愉快使用。
请确保 `github_id`, `repository_name`, `client_id`, `client_secret`正确填写。

这个是我的配置文件：
```yml
gitment:
  enable: true
  github_id: HeskeyBaozi # your github id
  repository_name: blog-prod-comments # your repository name

  # client_id & secret will generated after register an OAuth App
  # reference: https://github.com/settings/applications/new
  client_id: 005ba9093b6e776749ae
  client_secret: 2414f55a575d7986bfda2686d6f32a0551d2957e
  per_page: 8 # comments per page
  max_comment_height: 250 # default 250px
```
