### ISSUE TITLE
头像和背景图片无法载入

### ISSUE THREAD

**Issue by wushuaiping** [HeskeyBaozi/hexo-theme-lite#39]
```
avatar:
  enable: true
  url: /static/images/face.jpg

background:
  background_color: '#ffffff'

  # Custom Background Picture
  enable_picture: true
  url: /static/images/帝国大厦.jpg
  css_size: cover
  css_position: 50%
```
这是我的背景图已经头像配置，头像和背景图放在的是 `/Users/wushuaiping/blogs/themes/lite/static/images`下
